# This configuration file should be moved to `scripts/configs/sync.conf`
# For security reasons, `scripts/configs/` is not tracked by git.
# This file is provided here as an example to configure the
# synchronization of source code and results between the local machine
# and remote machines.
#
# You can add as many remotes as you want, one per line, using
# the standard rsync syntax. For example:
# username@remote:/path/to/remote/directory
#
# When calling `scripts/sync.sh`, all the source code files will be
# synchronized to the specified remotes, while the log and results
# files are synchronized from the remote to the local machine.
# This allows you to collect results from multiple remote machines,
# while keeping the source code in sync across all of them.
